# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f61b8d837c1bee754ef9b69dbbbf14e2ffaae00af73153112997a21af3624b62ce859673a59c88d6d3a1edc5777177f42cf77c7eac57f181b3ab65cbbda2e17c

test:
  secret_key_base: d319e72442a0d2cb36ea6c37b301ae8b3eafb43c14f5ce53dce29d08fb7426129ff450b22c86a70e93b38491d2bd9211c9f4ccad893eb77f7c6eb7c3aa598542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
